# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='translate.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z:github.com/protocolbuffers/protobuf/examples/go/tutorialpb',
  serialized_pb=b'\n\x0ftranslate.proto\"6\n\x07\x44\x65tails\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\";\n\x10TranslateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32\x08.Details\"<\n\x11TranslateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32\x08.Details2@\n\nTranslator\x12\x32\n\tTranslate\x12\x11.TranslateRequest\x1a\x12.TranslateResponseB<Z:github.com/protocolbuffers/protobuf/examples/go/tutorialpbb\x06proto3'
)




_DETAILS = _descriptor.Descriptor(
  name='Details',
  full_name='Details',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='Details.src', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='Details.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Details.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=73,
)


_TRANSLATEREQUEST = _descriptor.Descriptor(
  name='TranslateRequest',
  full_name='TranslateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='TranslateRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='TranslateRequest.details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=134,
)


_TRANSLATERESPONSE = _descriptor.Descriptor(
  name='TranslateResponse',
  full_name='TranslateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='TranslateResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='TranslateResponse.details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=196,
)

_TRANSLATEREQUEST.fields_by_name['details'].message_type = _DETAILS
_TRANSLATERESPONSE.fields_by_name['details'].message_type = _DETAILS
DESCRIPTOR.message_types_by_name['Details'] = _DETAILS
DESCRIPTOR.message_types_by_name['TranslateRequest'] = _TRANSLATEREQUEST
DESCRIPTOR.message_types_by_name['TranslateResponse'] = _TRANSLATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Details = _reflection.GeneratedProtocolMessageType('Details', (_message.Message,), {
  'DESCRIPTOR' : _DETAILS,
  '__module__' : 'translate_pb2'
  # @@protoc_insertion_point(class_scope:Details)
  })
_sym_db.RegisterMessage(Details)

TranslateRequest = _reflection.GeneratedProtocolMessageType('TranslateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATEREQUEST,
  '__module__' : 'translate_pb2'
  # @@protoc_insertion_point(class_scope:TranslateRequest)
  })
_sym_db.RegisterMessage(TranslateRequest)

TranslateResponse = _reflection.GeneratedProtocolMessageType('TranslateResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATERESPONSE,
  '__module__' : 'translate_pb2'
  # @@protoc_insertion_point(class_scope:TranslateResponse)
  })
_sym_db.RegisterMessage(TranslateResponse)


DESCRIPTOR._options = None

_TRANSLATOR = _descriptor.ServiceDescriptor(
  name='Translator',
  full_name='Translator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=198,
  serialized_end=262,
  methods=[
  _descriptor.MethodDescriptor(
    name='Translate',
    full_name='Translator.Translate',
    index=0,
    containing_service=None,
    input_type=_TRANSLATEREQUEST,
    output_type=_TRANSLATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSLATOR)

DESCRIPTOR.services_by_name['Translator'] = _TRANSLATOR

# @@protoc_insertion_point(module_scope)
